AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an Application Load Balancer

Parameters:
  CertificateArn:
    Type: String
    Description: ARN of the SSL certificate

Resources:
  pFinakALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyALB
      Subnets:
        - !Ref PublicSubnet
      SecurityGroups:
        - !Ref pFinakSecurityGroup
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60

  pTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: FinakTargetGroup
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: 80

  pListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref pTargetGroup
      LoadBalancerArn: !Ref pFinakALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateArn