name: Deploy AWS Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, stg, prod]  # Ambientes
        region: [us-east-1, us-west-1, eu-west-1]  # Regiones
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          echo "CLOUDFORMATION_TEMPLATES_DIR=$(pwd)/cloudformation" >> $GITHUB_ENV
          echo "PARAMS_DIR=$(pwd)/config/params-${{ matrix.environment }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region }}

      - name: Deploy CloudFormation Stack for VPC
        id: deploy-vpc
        run: |
          aws cloudformation deploy \
            --template-file ${{ env.CLOUDFORMATION_TEMPLATES_DIR }}/vpc-template.yaml \
            --stack-name finaktiva-vpc-stack-${{ matrix.environment }} \
            --parameter-overrides file://$${{ env.PARAMS_DIR }}/vpc-params.json \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Get VPC ID Output
        id: get-vpc-id
        run: |
          VPC_ID=$(aws cloudformation describe-stacks \
            --stack-name finaktiva-vpc-stack-${{ matrix.environment }} \
            --query "Stacks[0].Outputs[?OutputKey=='VPCId'].OutputValue" \
            --output text)
          echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV

      - name: Deploy CloudFormation Stack for Security Group
        run: |
          aws cloudformation deploy \
            --template-file ${{ env.CLOUDFORMATION_TEMPLATES_DIR }}/sg-template.yaml \
            --stack-name finaktiva-securitygroup-stack-${{ matrix.environment }} \
            --parameter-overrides VPCId=${{ env.VPC_ID }} file://$${{ env.PARAMS_DIR }}/sg-params.json \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_NAMED_IAM
